markdown: kramdown
kramdown:
  hard_wrap: true
url: http://utsargo.github.io
title: আবোল তাবোল
tagline: ""
timezone: Asia/Dhaka
description: "ইয়াদি কির্দ অত্র কাকালতনামা লিখিতং শ্রীকাক্কেশ্বর কুচ্‌কুচে কার্যঞ্চাগে…."
paginate: 10
fb_admins: http://facebook.com/utsargo.roy
fb_appid: 515675681947225
