---
title: স্বীকারোক্তি
timezone: Asia/Dhaka
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
subtitle: শতং বদ মা লিখ
email: royutsargo@gmail.com
description: আমি খুবই সহজ মানুষ। সোজা ভাবি, সোজা চলি, সোজা বলি, সোজা লিখি। কারো চিত্তবিনোদনের
  কোনো অভিপ্রায় নেই। যা কিছু লিখি তা আমার হৃদয়ের ছেঁড়া ছেঁড়া কথা। স্বীকারোক্তি।
baseurl: ''
url: https://blog.utsargo.work
plugins:
- jekyll-paginate
paginate: 5
paginate_path: "/page:num/"
logo: "/images/logo.png"
disqus: sbiikaarokti
markdown: kramdown
highlighter: rouge
kramdown:
  hard_wrap: true
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
author:
  name: উৎসর্গ রায়
  image: "/images/me.jpg"
  bio: সহজ লোক
  website: https://blog.utsargo.work
exclude:
- README.md
- Gemfile
- Gemfile.lock
- node_modules
- gulpfile.js
- package.json
- _site
- src
- vendor
- CNAME
- LICENSE
- Rakefile
sass:
  style: compressed
compress_html:
  clippings: all
  comments: all
  endings: all
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings:
  - html
  - head
  - body
fb_app_id: '1640233499610451'
fb_username: utsargo.roy
first_name: উৎসর্গ
last_name: রায়
gender: male
gems:
- jemoji
- jekyll-paginate
- jekyll-sass
- jekyll-sitemap
jekyll_admin:
  hidden_links:
    - posts
    - pages
    - staticfiles
    - datafiles
    - configuration